### ISSUE TITLE
Move and copy instructions for endian safe stores.

### ISSUE THREAD

**Issue by piyush-kurur** [piyush-kurur/verse-coq#19]
let us say that we have an array of bigendian Word16. How would we translate instructions like

```
x     :=  a[8] ; 
a[8]  := y ;

```
Where `x` and `y` are register variables. Often architectures have a byteswap instruction, so the first one is relatively easy. Load the register and do a byteswap when the endianness of a.
For the second one, we could byteswap and store but now the value in y is not valid. If we care about this value we will need to swap it back. We should provide two instructions; store and move. The former preserves the value in `y` (The code generated should swap y back) and the latter might not. The understanding is that users use the move instruction of the value in y is no more required as it  is one instruction less.

**Comment by piyush-kurur** [comment]
@dangabhi Can you have a go at these two instructions.

**Comment by piyush-kurur** [comment]
Here is the roadmap
- [ ] Add store and move instructions
- [ ] figure out a good notation for it.
- [ ] If possible generate proof obligations for checking use of moved variables before assignment.

**Comment by piyush-kurur** [comment]
@dangabhi Can you get this done ASAP. I would like to change the sample code in the paper by illustrating one code that does the message schedule for both Sha256 and Sha512. And it requires move instructions.
We can have the formulation of the semantics later on but if there is some instruction for the move then I can use it.

**Comment by dangabhi** [comment]
Ideal case the operation names and notations are self-explanatory, but in case not:
::== 'update2 nop' (no operation) is assignment (in particular without destruction in the wrong-endian case)
<== 'update2 mov' (move) is a move that can only be used with dereferenced arrays as target (might entail destruction)
