### ISSUE TITLE
Rename block to instructions

### ISSUE THREAD

**Issue by piyush-kurur** [piyush-kurur/verse-coq#28]
In `verse`-speak we have been calling a list of instructions as a block. When discussing  cryptography, blocks usually mean the block of data that a primitive processes. Therefore my suggestion is to rename block to
instructions (note s at the end which indicate plural).

@dangabhi please comment and I will make this changes.

In general it might be a good idea to use the plural form of something for denoting the list of that thing.

**Comment by dangabhi** [comment]
Cannot think of an alternative in the coding realm to 'block'. If the ambiguity matters, then instructions seems best. Was good to have blockCheck etc. is all. Those functions now become instructionsCheck I guess.

**Comment by piyush-kurur** [comment]
On Thu, Jan 25, 2018 at 10:02:06AM +0000, dangabhi wrote:
> Cannot think of an alternative in the coding realm to 'block'. If the ambiguity matters, then instructions seems best. Was good to have blockCheck etc. is all. Those functions now become instructionsCheck I guess.

Instructionscheck looks lame. So may be it does not make much sense to
change from `block` after all. Let me see how the writing goes and
then we can decide on it.

**Comment by piyush-kurur** [comment]
I am closing this issue with a wontfix as of now

**Comment by piyush-kurur** [comment]
It might make sense to think of a better name, may be code.

**Comment by dangabhi** [comment]
This was a comment in #31 
>Don't see any possible objection.
Other possible name-changes - 
>* block could become 'code' or 'codeBlock' (mostly cause you wanted to move away from block)
>* if 'body' becomes 'verse', then 'statements' (the tactic) could become 'body'
