### ISSUE TITLE
Rename the `body` tactic to verse.

### ISSUE THREAD

**Issue by piyush-kurur** [piyush-kurur/verse-coq#31]
Currently we have the `body` tactic that takes care of disposing proof obligations that prove that indexing is always less than the bound. I would like to rename this as `verse`. The `body` tactic is going to be the one
that does a lot of heavy lifting and should be seen as a teleportation from the `coq` world to the world of `verse`. It therefore makes sense to rename it as `verse`. One can think of this like the `asm`  key word that many Compilers support to escape to the world of assembly.

@dangabhi signoff on this and I will implement this.

**Comment by dangabhi** [comment]
Don't see any possible objection.
Other possible name-changes - 
* block could become 'code' or 'codeBlock' (mostly cause you wanted to move away from block)
* if 'body' becomes 'verse', then 'statements' (the tactic) could become 'body'

**Comment by piyush-kurur** [comment]
This sounds good. Particularly the other name changes that you suggest. `block`  is a type and not a tactic so
one can name `block ` also as `verse` or just maybe `program`.  Renaming `block` to `verse`  will not conflict with the tactic of the same name. I will only make the change from body to verse leaving the other changes for time being.
