### ISSUE TITLE
New name for destroy and an additional instruction

### ISSUE THREAD

**Issue by piyush-kurur** [piyush-kurur/verse-coq#40]
We have been using the pseudo-instruction `destroy` to make a variable not fit for use in the rest of the code. In the IRC discussion we recognised that this could be confusing as often in cryptography we do want to erase secrets to avoid its leak. I suggest the following:

- [ ] Rename `destroy` to `INVALIDATE`  (we can use the convention that all caps for such instructions)
- [ ] Add and instruction `ERASE` for erasing the value held in a variable, typically done to avoid leaking secrets.  

The semantics for these instructions are the following

- `INVALIDATE` is essentially a nop but results in the variable being unavailable for use.
-  `ERASE` actually fills the variable with a zero or some fixed constant like `42`. For the verse programmer   `ERASE` is like `INVALIDATE` as the value is not available subsequently. However, in code generation it
cannot be a noop as there should be code that actually does the earsure (Xor A A) can be used for example.

@dangabhi please comment.

**Comment by dangabhi** [comment]
Doesn't ERASE go against the keep-instruction-set-low-level? I am guessing semantically we are going to assume ERASE INVALIDATEs; but that might have minor issues. Say an XOR DX DX was done to zero something out, but then it is more efficient to increment DX to set it to 1 (which happens to be required) rather than to set it to 1. We'll end up disallowing that.

Consider FREE for INVALIDATE? It just looks odd to write 'INVALIDATE DX; DX += AX'
I am drawing a parallel from the pointer free'ing concept. Kinda frees the current 'reference'; comes with no constructive guarantee, but a destructive possibility.

**Comment by piyush-kurur** [comment]
The user should not assume what erase does. It is meant to prevent data from leaking out. It could be filling the register with zero or it could be doing something else. The difference between invalidate and erase is the following. invalidate says "you are not allowed to use it anymore untill you set it". So free is not really a good name. Whereas erase means invalidate + ensure what ever content was present cannot be recovered. 
Another option is not to have erase but support it with macro like foreach. I am okey with that too

**Comment by dangabhi** [comment]
I like the macro idea much more than making it an instruction - for anything that is going to be a sequence of instructions we provide anyway.
Maybe consider naming it with a non-verb, more like a declaration; since it is in the spirit of an annotation rather than an instruction.

**Comment by piyush-kurur** [comment]
What about calling the destroy instruction clobber, a word that is used in compilers like GCC to say that a register is modified as a side effect.

**Comment by dangabhi** [comment]
Still a verb :) , but the best amongst them I guess. It does mean (in context) exactly what it should.

**Comment by piyush-kurur** [comment]
Why do you not like a verb. If you look at the assembly instruction, they are all verbs add subtract etc. Also there is the act of clobbering a register so I think clobber sounds good. It also conveys the meaning that clobber results in the data being modified in a disadvantageous way (for example one should not assume that clobbering the register would lead to protection against secret leaks.

**Comment by dangabhi** [comment]
'Clobber' (for want of a better name :) ) does not have a (real) semantic footprint, and thus is not an 'action'; thence the aversion to verbs.
I still think clobber is more along the lines of an 'annotation' and not an 'instruction'; but I am ok with the name change, even if for no other reason than that I cannot come up with a good alternative.
